version: '3'
services:
  banking-app:
    build:
      context: .
      dockerfile: Dockerfile
    user: 1000:1000
    volumes:
      - .:/var/www/html
  email-testing:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"